### ISSUE TITLE
ReferenceError: url is not defined

### ISSUE THREAD

**Issue by ruze00** [PlonkaAdam/SafariBooks-Downloader#1]
Hi, I followed your fork from the original one since I was getting the `err: RequestError: getaddrinfo ENOTFOUND` error.  However, the first time I tried to run your version I get the following:

[...]/workspace/SafariBooks-Downloader/lib/safari/index.js:114
  debug(`fetchResource called with URL: ${url}`);
                                          ^

ReferenceError: url is not defined
    at Object.<anonymous> ([...]/workspace/SafariBooks-Downloader/lib/safari/index.js:114:43)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> ([...]/workspace/SafariBooks-Downloader/lib/cli/index.js:7:16)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> ([...]/workspace/SafariBooks-Downloader/index.js:11:18)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

Any ideas?

**Comment by auqib-naik** [comment]
fork for the fix: https://github.com/auqib-naik/SafariBooks-Downloader.git
